# 使用轻量级的 Python 3.9 镜像作为基础
FROM python:3.9-slim

# 设置工作目录
WORKDIR /app

# 复制项目文件到容器中
COPY requirements.txt .
COPY main.py .
COPY config.py .
COPY database.py .
COPY utils.py .
COPY modules/ modules/

# 安装项目依赖
RUN pip install --no-cache-dir -r requirements.txt

# 启动应用
CMD ["python", "main.py"]