FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
COPY main.py .
COPY config.py .
COPY database.py .
COPY utils.py .
COPY modules/ modules/

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "main.py"]
