FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY main.py .
COPY config.py .
COPY database.py .
COPY utils.py .
COPY modules/ modules/

CMD ["python", "main.py"]
